spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cashbackengine}
    username: ${POSTGRES_USER:cashback_user}
    password: ${POSTGRES_PASSWORD:cashback_pass}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

management:
  health:
    mail:
      enabled: false

logging:
  level:
    com.cashback: INFO
